### ISSUE TITLE
Installation/ Importing Issues with Anaconda pip

### ISSUE THREAD

**Issue by JohnsCBAC** [adimajo/lrtree#1]
Installation through Anaconda using `pip` issue. When importing package `from lrtree import Lrtree` after installation it
 raises a `ModuleNotFoundError` error message. Message included below:

<img width="488" alt="lrtree ModulNotFoundError" src="https://user-images.githubusercontent.com/90399819/207040100-459f7312-f645-4624-af96-fd12d9a81b82.PNG">

**Comment by adimajo** [comment]
Thanks; the `scripts` module was probably not included in the distribution at that time. I'll try fixing this in the next few days by updating the version distributed on PyPi.

**Comment by JohnsCBAC** [comment]
Thank you. Is this likely to be fixed soon?

**Comment by adimajo** [comment]
Should be fixed in versions > 1.0.0; might as well install latest version (1.0.4 as of now)! Let me know how that turns out, and sorry for the delay!
